### ISSUE TITLE
Update composer.json and tag releases

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel-ng-artisan-generators#3]
Hi @m33ch 

Would you mind if I change the namespace to make it inline with the repo as well? Let me know

And I'll start tagging the 1.0 release after I add the tests (since this has already been used by many users on the original repo)

**Comment by m33ch** [comment]
Of course. I also was thinking of changing the namespace.

Laraplate\ngGenerators ??
Il 04 nov 2015 10:42 PM, "Jad Joubran" notifications@github.com ha
scritto:

**Comment by jadjoubran** [comment]
The problem is that `Laraplate` did not make it on the trello board..
How about `LaravelAngular\generators`
What do you think?

**Comment by m33ch** [comment]
Ok perfect!

The problem is that Laraplate did not make it on the trello board..
How about LaravelAngular\generators
What do you think?

**Comment by jadjoubran** [comment]
Okay let me know if you want to do it or if you want me to do it
Cheers man

**Comment by m33ch** [comment]
I can do it tomorrow morning. But if you want to do now, go on!
Il 04 nov 2015 11:00 PM, "Jad Joubran" notifications@github.com ha
scritto:

**Comment by jadjoubran** [comment]
It's fine take your time!

**Comment by jadjoubran** [comment]
Done
