### ISSUE TITLE
Indent Size

### ISSUE THREAD

**Issue by nueko** [jadjoubran/laravel-ng-artisan-generators#37]
Hi, how about 2 indent size?

**Comment by jadjoubran** [comment]
Hi @nueko 
For the stubs? as in the generated files

**Comment by nueko** [comment]
yes, for the stubs, or maybe configurable indent size.

**Comment by jadjoubran** [comment]
The codebase for Angular material is using tabs with indent size 4 so it wouldn't make sense to change it to size 2
Configuration would be too complicated, what we can do in the future, is maybe allow publishing those templates so users can edit them as they see fit
