### ISSUE TITLE
Laravel 5.4.x?

### ISSUE THREAD

**Issue by james-coder** [jadjoubran/laravel-ng-artisan-generators#40]
Is there planned support for Laravel 5.4.x? (Or known incompatibilities?) This package seems to be restricted to 5.3.x right now.

**Comment by jadjoubran** [comment]
Hi @jamesalton 
It should probably work for 5.4.x except for the restriction in composer.json
Would you mind sending a PR?

**Comment by james-coder** [comment]
Created https://github.com/jadjoubran/laravel-ng-artisan-generators/pull/41
(With a very small amount of testing. Seems to work.)
